unit EditBone.Consts;

interface

const
  EDITBONE_MAIN_CAPTION_DOCUMENT = ' - [%s]';
  EDITBONE_STATUS_BAR_PANEL_WIDTH = 88;
  EDITBONE_STATUS_BAR_HINT_PANEL = 4;
  { Tab sheet item tags }
  EDITBONE_EDITOR_TAG = 0;
  EDITBONE_SPLIT_EDITOR_TAG = 1;
  EDITBONE_XML_TREE_TAG = 2;
  EDITBONE_VERTICAL_SPLITTER_TAG = 3;
  EDITBONE_COMBOBOX_SEARCH_TEXT_TAG = 4;
  EDITBONE_HORIZONTAL_SPLITTER_TAG = 5;
  EDITBONE_SEARCH_PANEL_TAG = 6;
  EDITBONE_LABEL_SEARCH_RESULT_COUNT_TAG = 7;

implementation

end.
