unit EditBone.Consts;

interface

const
  EDITBONE_MAIN_CAPTION_DOCUMENT = ' - [%s]';
  EDITBONE_STATUS_BAR_PANEL_WIDTH = 86;
  EDITBONE_STATUS_BAR_HINT_PANEL = 4;
  { Tab sheet item tags }
  EDITBONE_EDITOR_TAG = 0;
  EDITBONE_SPLIT_EDITOR_TAG = 1;
  EDITBONE_XML_TREE_TAG = 2;
  EDITBONE_VERTICAL_SPLITTER_TAG = 3;
  EDITBONE_COMBOBOX_TAG = 4;

implementation

end.
